server:
  port: 8803
spring:
  kafka:
    consumer:
      group-id: notification_tracker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kss.notificationtracker.utils.NotificationDeserializer
    bootstrap-servers: 10.199.100.13:9092
  application:
    name: notification-tracker
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  data:
    mongodb:
      host: 10.199.100.13
      port: 27017
      username: mongodb
      password: mongodb
      authentication-database: admin
      database: notification_tracker

#management:
#  endpoint:
#    prometheus:
#      enabled: true
#    metrics:
#      enabled: true
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#        pushgateway:
#          enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus, metrics
