server:
  port: 8804
spring:
  kafka:
    consumer:
      group-id: notification_tracker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kss.notificationtracker.utils.NotificationDeserializer
    bootstrap-servers: 10.199.100.13:9092
  application:
    name: notification-tracker
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    hikari:
      maxLifetime: '2000000'
      connectionTimeout: '30000'
      minimumIdle: '50'
      poolName: HikariPoolUserManagementService
      idleTimeout: '30000'
      maximumPoolSize: '500'
    driver-class-name: org.mariadb.jdbc.Driver
    username: user_management
    password: bTUEp4d4JrS5vNAe
    url: jdbc:mariadb://10.199.200.7:3306,10.199.200.8:3306,10.199.200.9:3306:3306/user_management?autoReconnect=true
  jpa:
    show-sql: true

logging:
  level:
    root: debug
